spring:
  application:
    name: alerta-service

  main:
    web-application-type: none

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:admin}
    password: ${RABBITMQ_PASSWORD:secret}

client:
  tratamento-api:
    base-url: ${TRATAMENTO_API_BASE_URL:http://localhost:8080/api/v1/}
