spring:
  application:
    name: alerta-service

  main:
    web-application-type: none

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:admin}
    password: ${RABBITMQ_PASSWORD:secret}

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:email_do_sender@gmail.com}
    password: ${MAIL_PASSWORD:XXXX YYYY ZZZZ WWWW}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

alerta:
  email:
    destinatario: ${ALERTA_EMAIL_DESTINATARIO:email_recebedor_alerta@gmail.com}

client:
  tratamento-api:
    base-url: ${TRATAMENTO_API_BASE_URL:http://localhost:8080/api/v1/}
